//! Normal vector estimation for 3D point clouds.
//!
//! Provides triangle-based normal vector calculation and RANSAC-based
//! plane fitting with normal vector estimation.

use nalgebra::Vector3;
use rand::prelude::IndexedRandom;
use rand::SeedableRng;
use rand_distr::{Distribution, Normal};

/// Calculate the unit normal vector of a triangle defined by three 3D points.
///
/// The normal direction follows the right-hand rule with respect to
/// the ordering (p1 -> p2, p1 -> p3).
///
/// # Panics
/// Panics if the three points are collinear (cross product is zero).
pub fn calc_normal_vector(p1: &Vector3<f64>, p2: &Vector3<f64>, p3: &Vector3<f64>) -> Vector3<f64> {
    let v1 = p2 - p1;
    let v2 = p3 - p1;
    let normal = v1.cross(&v2);
    let norm = normal.norm();
    assert!(norm > 1e-12, "Points are collinear, cannot compute normal");
    normal / norm
}

/// Compute the distance from a point to a plane defined by a normal and an origin point.
pub fn distance_to_plane(
    point: &Vector3<f64>,
    normal: &Vector3<f64>,
    origin: &Vector3<f64>,
) -> f64 {
    let dot = normal.dot(point) - normal.dot(origin);
    if dot.abs() < 1e-15 {
        0.0
    } else {
        dot.abs() / normal.norm()
    }
}

/// Result of RANSAC normal vector estimation.
#[derive(Debug, Clone)]
pub struct RansacResult {
    /// Center (mean) of the point cloud.
    pub center: Vector3<f64>,
    /// Estimated unit normal vector of the best-fit plane.
    pub normal: Vector3<f64>,
}

/// Estimate the normal vector of a plane from a 3D point cloud using RANSAC.
///
/// # Arguments
/// * `points` - Slice of 3D points.
/// * `inlier_ratio_threshold` - Stop early if the inlier ratio exceeds this value.
/// * `inlier_dist` - Maximum distance from the plane for a point to be considered an inlier.
/// * `confidence` - Probability that at least one sample set is outlier-free (e.g. 0.99).
/// * `seed` - Random seed for reproducibility.
///
/// # Returns
/// `Some(RansacResult)` if a valid plane is found, `None` otherwise.
pub fn ransac_normal_vector_estimation(
    points: &[Vector3<f64>],
    inlier_ratio_threshold: f64,
    inlier_dist: f64,
    confidence: f64,
    seed: u64,
) -> Option<RansacResult> {
    if points.len() < 3 {
        return None;
    }

    let center: Vector3<f64> = points.iter().copied().sum::<Vector3<f64>>() / points.len() as f64;

    let max_iter =
        ((1.0 - confidence).ln() / (1.0 - (1.0 - inlier_ratio_threshold).powi(3)).ln()) as usize;

    let mut rng = rand::rngs::StdRng::seed_from_u64(seed);
    let indices: Vec<usize> = (0..points.len()).collect();

    for _iter in 0..max_iter {
        // Sample 3 distinct points
        let sampled: Vec<&usize> = indices.choose_multiple(&mut rng, 3).collect();
        let p1 = &points[*sampled[0]];
        let p2 = &points[*sampled[1]];
        let p3 = &points[*sampled[2]];

        // Skip degenerate triangles
        let v1 = p2 - p1;
        let v2 = p3 - p1;
        if v1.cross(&v2).norm() < 1e-12 {
            continue;
        }

        let normal = calc_normal_vector(p1, p2, p3);

        let n_inliers = points
            .iter()
            .filter(|p| distance_to_plane(p, &normal, &center) <= inlier_dist)
            .count();
        let inlier_ratio = n_inliers as f64 / points.len() as f64;

        if inlier_ratio > inlier_ratio_threshold {
            return Some(RansacResult { center, normal });
        }
    }

    None
}

/// Generate 3D points sampled from a plane with optional Gaussian noise.
///
/// Useful for testing. Points are generated by projecting random 2D points
/// onto a plane with the given normal vector.
pub fn sample_points_on_plane(
    num_samples: usize,
    normal: &Vector3<f64>,
    noise_scale: f64,
    seed: u64,
) -> Vec<Vector3<f64>> {
    let mut rng = rand::rngs::StdRng::seed_from_u64(seed);
    let dist = Normal::new(0.0, 1.0).unwrap();
    let noise_dist = Normal::new(0.0, noise_scale).unwrap();
    let unit_normal = normal.normalize();

    // Generate 2D points and project onto the plane
    let mut points_2d: Vec<Vector3<f64>> = Vec::with_capacity(num_samples);
    for _ in 0..num_samples {
        let x = dist.sample(&mut rng);
        let y = dist.sample(&mut rng);
        points_2d.push(Vector3::new(x, y, 0.0));
    }

    // Compute mean offset d
    let d: f64 = points_2d.iter().map(|p| unit_normal.dot(p)).sum::<f64>() / num_samples as f64;

    // Project points onto the plane
    let mut points_3d: Vec<Vector3<f64>> = Vec::with_capacity(num_samples);
    for p2d in &points_2d {
        let proj_len = (d - unit_normal.dot(p2d)) / unit_normal.norm_squared();
        let mut p3d = p2d + proj_len * unit_normal;
        // Add noise
        p3d.x += noise_dist.sample(&mut rng);
        p3d.y += noise_dist.sample(&mut rng);
        p3d.z += noise_dist.sample(&mut rng);
        points_3d.push(p3d);
    }

    points_3d
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_calc_normal_vector_xy_plane() {
        let p1 = Vector3::new(0.0, 0.0, 0.0);
        let p2 = Vector3::new(1.0, 0.0, 0.0);
        let p3 = Vector3::new(0.0, 1.0, 0.0);
        let n = calc_normal_vector(&p1, &p2, &p3);
        // Normal should be along z-axis
        assert!((n.x.abs()) < 1e-10);
        assert!((n.y.abs()) < 1e-10);
        assert!((n.z.abs() - 1.0) < 1e-10);
    }

    #[test]
    fn test_calc_normal_vector_unit_length() {
        let p1 = Vector3::new(0.0, 0.0, 1.0);
        let p2 = Vector3::new(1.0, 1.0, 0.0);
        let p3 = Vector3::new(0.0, 1.0, 0.0);
        let n = calc_normal_vector(&p1, &p2, &p3);
        assert!((n.norm() - 1.0).abs() < 1e-10);
    }

    #[test]
    #[should_panic]
    fn test_calc_normal_vector_collinear_panics() {
        let p1 = Vector3::new(0.0, 0.0, 0.0);
        let p2 = Vector3::new(1.0, 1.0, 1.0);
        let p3 = Vector3::new(2.0, 2.0, 2.0);
        calc_normal_vector(&p1, &p2, &p3);
    }

    #[test]
    fn test_distance_to_plane() {
        let origin = Vector3::new(0.0, 0.0, 0.0);
        let normal = Vector3::new(0.0, 0.0, 1.0);
        let point = Vector3::new(3.0, 4.0, 5.0);
        let d = distance_to_plane(&point, &normal, &origin);
        assert!((d - 5.0).abs() < 1e-10);
    }

    #[test]
    fn test_distance_to_plane_on_plane() {
        let origin = Vector3::new(0.0, 0.0, 0.0);
        let normal = Vector3::new(0.0, 0.0, 1.0);
        let point = Vector3::new(3.0, 4.0, 0.0);
        let d = distance_to_plane(&point, &normal, &origin);
        assert!(d.abs() < 1e-10);
    }

    #[test]
    fn test_ransac_with_perfect_plane() {
        // Points exactly on the z=0 plane
        let points: Vec<Vector3<f64>> = vec![
            Vector3::new(0.0, 0.0, 0.0),
            Vector3::new(1.0, 0.0, 0.0),
            Vector3::new(0.0, 1.0, 0.0),
            Vector3::new(1.0, 1.0, 0.0),
            Vector3::new(0.5, 0.5, 0.0),
            Vector3::new(-1.0, 0.5, 0.0),
            Vector3::new(0.3, -0.7, 0.0),
            Vector3::new(-0.5, -0.5, 0.0),
            Vector3::new(2.0, 0.0, 0.0),
            Vector3::new(0.0, 2.0, 0.0),
        ];

        let result = ransac_normal_vector_estimation(&points, 0.7, 0.01, 0.99, 42);
        assert!(result.is_some());
        let res = result.unwrap();
        // Normal should be along z-axis (up to sign)
        assert!(res.normal.z.abs() > 0.99);
    }

    #[test]
    fn test_ransac_with_noisy_plane() {
        let true_normal = Vector3::new(0.0, 1.0, 1.0).normalize();
        let noise_scale = 0.05;
        let points = sample_points_on_plane(100, &true_normal, noise_scale, 12345);

        let result = ransac_normal_vector_estimation(&points, 0.6, noise_scale * 3.0, 0.99, 42);
        assert!(result.is_some());
        let res = result.unwrap();
        // Estimated normal should be close to true normal (up to sign)
        let dot = res.normal.dot(&true_normal).abs();
        assert!(
            dot > 0.9,
            "Estimated normal too far from true normal: dot={}",
            dot
        );
    }

    #[test]
    fn test_ransac_too_few_points() {
        let points = vec![Vector3::new(0.0, 0.0, 0.0), Vector3::new(1.0, 0.0, 0.0)];
        let result = ransac_normal_vector_estimation(&points, 0.7, 0.1, 0.99, 42);
        assert!(result.is_none());
    }

    #[test]
    fn test_sample_points_on_plane_count() {
        let normal = Vector3::new(0.0, 0.0, 1.0);
        let pts = sample_points_on_plane(50, &normal, 0.0, 0);
        assert_eq!(pts.len(), 50);
    }
}
